---
# Ansible playbook for a LAMP server.
#
# If this is being used within a Vagrant profile, you can update your server
# by running `vagrant provision` again.
#
# @author Jeff Geerling (2014).

- hosts: lemp
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.repo-epel
    - geerlingguy.repo-remi
    - geerlingguy.mysql
    - geerlingguy.nginx
    - geerlingguy.php
