---
# Ansible playbook for an SVN server.
#
# If this is being used within a Vagrant profile, you can update your server
# by running `vagrant provision` again.
#
# @author Jeff Geerling (2014).

- hosts: svn
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.apache
    - geerlingguy.svn
