---
# Ansible playbook for a Git2Svn server.
#
# If this is being used within a Vagrant profile, you can update your server
# by running `vagrant provision` again.
#
# @author Jeff Geerling (2014).

- hosts: svn2git
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.svn
    - geerlingguy.git
    - geerlingguy.svn2git
