---
# Ansible playbook for an Apache Solr server.
#
# @author Jeff Geerling (2015).

- hosts: solr
  gather_facts: yes

  vars:
    firewall_allowed_tcp_ports:
      - "22"
      - "8983"

  roles:
    - geerlingguy.firewall
    - geerlingguy.java
    - geerlingguy.solr
