---
# Ansible playbook for an AWX server.
#
# @author Jeff Geerling (2017).

- hosts: awx
  gather_facts: yes
  become: yes

  vars:
    awx_installation_directory: "~/awx/"
    nodejs_version: "6.x"
    pip_install_packages:
      - name: docker-py

  pre_tasks:
    - name: Install dependencies.
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - gettext
        - gcc-c++
        - bzip2

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.git
    - geerlingguy.ansible
    - geerlingguy.docker
    - geerlingguy.pip
    - geerlingguy.nodejs

  tasks:
    # TODO: Make this idempotent.
    - name: Add GitHub's host key to known_hosts.
      command: ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Ensure AWX repository is cloned.
      git:
        repo: 'https://github.com/ansible/awx.git'
        dest: "{{ awx_installation_directory }}"
        version: master

    - name: Run the AWX installation playbook.
      command: ansible-playbook -i inventory install.yml
      args:
        chdir: "{{ awx_installation_directory }}"

    - name: Install AWX using a shell script.
      script: files/install-awx-centos7.sh
      args:
        creates: /path/to/file/created
