---
- src: geerlingguy.java
- src: geerlingguy.nginx
- src: geerlingguy.elasticsearch
  version: 2.1.2
- src: geerlingguy.elasticsearch-curator
  version: 1.0.7
- src: geerlingguy.kibana
  version: 2.0.1
- src: geerlingguy.logstash
  version: 3.0.0
- src: geerlingguy.filebeat
  version: 1.0.0
