---
- hosts: localhost
  sudo: yes

  tasks:
    - name: Get host IP address.
      shell: "/sbin/ip route|awk '/default/ { print $3 }'"
      register: host_ip
      changed_when: false

    - name: Set host_ip_address variable.
      set_fact:
        host_ip_address: "{{ host_ip.stdout }}"

    - name: Ensure www directory exists.
      file:
        path: /opt/www
        state: directory
        mode: 0755

    - name: Install Python MySQL dependencies.
      apt: "name={{ item }} state=present"
      with_items:
        - libmysqlclient-dev
        - python-dev

    - name: Install Flask and SQLAlchemy.
      pip: "name={{ item }} state=present"
      with_items:
        - flask
        - flask-sqlalchemy
        - mysql-python

    - name: Copy Flask app into place.
      template:
        src: /etc/ansible/index.py.j2
        dest: /opt/www/index.py
        mode: 0755

    - name: Copy Flask templates into place.
      copy:
        src: /etc/ansible/templates
        dest: /opt/www
        mode: 0755
