---
# Ansible playbook for a Munin monitoring server.
#
# If this is being used within a Vagrant profile, you can update your server
# by running `vagrant provision` again.
#
# @author Jeff Geerling (2014).
#
# @see http://www.ansibleworks.com/docs/bestpractices.html

- hosts: munin
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.repo-epel
    - geerlingguy.apache
    - geerlingguy.munin
    - geerlingguy.munin-node
